Remove cloudsmith repo from portal
TykTechnologies/gromit pull request #103
Opened 2022-12-23 10:30 UTC by ermirizio

2022-12-23 16:43 UTC, alephnull requested changes

2022-12-23 16:43 UTC, alephnull commented on policy/templates/releng/.github/workflows/release.yml.d/goreleaser.tmpl
> +  {{- if ne .Name "portal" }}
I think this might be better served by have a parameter for non-oss repos

2023-01-09 14:36 UTC, ermirizio commented
@alephnull , @asutosh Could you please review this one again? I have made the changes already

2023-01-09 16:18 UTC, alephnull approved these changes

2023-01-09 16:18 UTC, merged