Implements control points for pr, lts pr, tag
TykTechnologies/gromit pull request #242
Opened 2023-12-26 07:44 UTC by alephnull

2023-12-26 12:08 UTC, ermirizio requested changes
Please add printing of the calculated versions after line 63

2023-12-27 07:39 UTC, alephnull commented
> Please add printing of the calculated versions after line 63

See debug logs at https://github.com/TykTechnologies/tyk-pump/actions/runs/7335877466/job/19974434967?pr=757#step:7:41

2023-12-27 09:27 UTC, alephnull commented
https://tyktech.atlassian.net/browse/SYSE-87?focusedCommentId=48101 blocks merging.

2024-01-12 07:50 UTC, asutosh submitted a review, later dismissed

2024-01-12 11:31 UTC, ermirizio requested changes

2024-01-12 11:31 UTC, ermirizio commented on policy/templates/releng/.github/workflows/release.yml
> +          IS_LTSPR: {{`${{(startsWith(github.event_name, 'pull_request') && endsWith(github.base_ref, '-lts')) && 'yes' }}`}}
```suggestion
          IS_LTS: {{`${{(startsWith(github.event_name, 'pull_request') && endsWith(github.base_ref, '-lts')) && 'yes' }}`}}
```

2024-01-15 20:57 UTC, ermirizio approved these changes

2024-01-15 20:57 UTC, merged