TD-1305/automerge-gromit-option2
TykTechnologies/gromit pull request #77
Opened 2022-11-07 19:44 UTC by ermirizio

2022-11-08 02:05 UTC, alephnull requested changes
Thanks for this. It looks fine except for some minor style related things.

2022-11-08 02:05 UTC, alephnull commented on policy/policy.go
> +		} else {
Is this else required? The return in the other branch ensures that control will never reach this point in the case of an error.

2022-11-08 21:04 UTC, ermirizio commented on cmd/policy.go
> +	policyCmd.PersistentFlags().BoolVarP(&autoMerge, "auto", "a", false, "Will automerge if all requirements are meet")
Felt the same

2022-11-09 02:54 UTC, alephnull approved these changes
Needs a rebase.

2022-11-09 09:28 UTC, merged